cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.add_to_cart, name='add_to_cart'),
]

djangomine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/', views.category_list, name='category_list'),
]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.urls import reverse
from django.utils.safestring import mark_safe


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='category/', blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='brands/')

    class Meta:
        verbose_name_plural = 'Brands'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='brand_product', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" heights="70" width="60" />'.format(self.image.url))

    image_tag.short_description = 'Image'

    def imageURL(self):
        if self.image:
            return self.image.url
        else:
            return ""

    def get_absolute_url(self):
        return reverse('store:product_detail', kwargs={'slug': self.slug})


class Banner(models.Model):
    img = models.ImageField(upload_to="banners/")
    alt_text = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="100" />' % (self.img.url))

    def __str__(self):
        return self.alt_text

cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

# Create your views here.
from cart.cart import Cart
from store.models import Product


def cart_summary(request):
    return render(request, 'store/cart/summary.html')


def add_to_cart(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)
        response = JsonResponse({'qty': product_qty})

        return response

store/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.
from .models import Banner, Brand, Category, Product


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product': product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}BeeShop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
            integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
            integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
            crossorigin="anonymous"></script>


</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">BeeShop</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'store:product_all' %}">All</a></li>
                            {% for c in categories %}
                                <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
            <a href="{% url 'cart:cart_summary' %}" type="button" role="button" class="btn btn-outline-secondary">
                {% with total_qty=basket|length %}
                    <div id="cart-qty" class="d-inline-flex">
                        {% if total_qty > 0 %}
                            {{ total_qty }}
                        {% else %}
                            0
                        {% endif %}
                    </div>
                {% endwith %}
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket"
                     viewBox="0 0 16 16">
                    <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z"/>
                </svg>
                Cart
            </a>
        </div>
    </nav>
</header>
<div id="content">{% block content %}{% endblock %}</div>
</body>
</html>

templates/store/cart/summary.html
{% extends 'store/base.html' %}
{% block title %}
Cart Summary
{% endblock title %}

{% block content %}
Cart
{% endblock content %}

templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}BeeShop | Home{% endblock title %}
{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-3">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
                <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A animi asperiores
                    autem beatae cupiditate dicta error, eveniet modi natus placeat porro recusandae sit. Ad alias
                    beatae, commodi dignissimos doloribus eligendi et illum iure laborum libero magni neque non nostrum
                    obcaecati, porro possimus quaerat quas quia sed totam. Accusantium, culpa eius.</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Make an account</a>
                </p>
            </div>
        </div>
    </section>


    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">All Products</div>
            <div class="row row-colls-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <a href="{{ product.get_absolute_url }}"><img class="img-fluid" src="{{ product.imageURL }}" alt=""></a>
                                <p class="card-text"><a href="{{ product.get_absolute_url }}">{{ product.title|title }}</a></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                    </div>
                                    <small class="text-muted">֏ {{ product.price }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/store/products/category.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}Category | {{ category.name }}{% endblock %}

{% block content %}
<div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">{{ category.name|title }}</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <a href="{{ product.get_absolute_url }}"><img class="img-fluid" src="{{ product.imageURL }}" alt=""></a>
                                <p class="card-text"><a href="{{ product.get_absolute_url }}">{{ product.title|title }}</a></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                    </div>
                                    <small class="text-muted">֏ {{ product.price }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/store/products/single.html
{% extends 'store/base.html' %}
{% block title %}
    {{ product.name }}
{% endblock title %}
{% block content %}

    <div class="container">
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img src="{{ product.imageURL }}" class="img-fluid mx-auto d-block" width="auto" alt="">
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ product.title }}</h1>
                    <p><span class="lead">{{ product.brand }}</span></p>
                    <p>{{ product.description|slice:":355" }}...</p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6">Price</div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">֏ {{ product.price }}</span></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row p-3">
                                <div class="col-6">
                                    <label for="select">Qty</label>
                                    <select id="select">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </div>
                                <div class="col-6 text-end">
                                    <button type="button" id="add-button" value="{{ product.id }}"
                                            class="btn btn-secondary btn-sm">Add to cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url 'cart:add_to_cart' %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post',
                },
                success: function (json) {
                    document.getElementById('cart-qty').innerHTML = json.qty
                },
                error: function (xhr, errmsg, err) {

                }
            })
        })
    </script>

{% endblock %}